name: Build CODM Tutorial Skip

on:
  workflow_dispatch:

  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-24.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4


      - name: Find Android NDK
        shell: bash
        run: |
          set -eux

          NDK="$(find /usr/local/lib/android/sdk/ndk \
            -maxdepth 1 \
            -mindepth 1 \
            -type d \
            | sort -V \
            | tail -n1)"

          echo "Using NDK: $NDK"

          echo "ANDROID_NDK_HOME=$NDK" \
            >> "$GITHUB_ENV"

          test -x "$NDK/ndk-build"


      - name: Download Zygisk API
        shell: bash
        run: |
          set -eux

          curl -L \
            https://raw.githubusercontent.com/topjohnwu/zygisk-module-sample/master/module/jni/zygisk.hpp \
            -o jni/zygisk.hpp

          test -s jni/zygisk.hpp


      - name: Build
        shell: bash
        run: |
          set -eux

          "$ANDROID_NDK_HOME/ndk-build" \
            NDK_PROJECT_PATH="$GITHUB_WORKSPACE" \
            APP_BUILD_SCRIPT="$GITHUB_WORKSPACE/jni/Android.mk" \
            NDK_APPLICATION_MK="$GITHUB_WORKSPACE/jni/Application.mk" \
            NDK_OUT="$GITHUB_WORKSPACE/build/obj" \
            NDK_LIBS_OUT="$GITHUB_WORKSPACE/build/libs"


      - name: Prepare module
        shell: bash
        run: |
          set -eux

          rm -rf out

          mkdir -p \
            out/zygisk

          cp \
            module/module.prop \
            out/module.prop

          cp \
            module/action.sh \
            out/action.sh

          cp \
            module/service.sh \
            out/service.sh

          cp \
            build/libs/arm64-v8a/libcodm_tutorial_skip.so \
            out/zygisk/arm64-v8a.so

          chmod 0755 \
            out/action.sh \
            out/service.sh


      - name: Create ZIP
        shell: bash
        run: |
          set -eux

          cd out

          zip \
            -9 \
            -r \
            ../CODM-Tutorial-Skip.zip \
            .


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: CODM-Tutorial-Skip
          path: CODM-Tutorial-Skip.zip
